monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
        grouped:
            type:    group
            members: [rotating_file, deduplicated]
        rotating_file:
            type:      rotating_file
            path:      "%kernel.logs_dir%/%kernel.environment%.log"
            level:     debug
            max_files: 10
            channels:  ["!event"]
        deduplicated:
            type:    deduplication
            time:    10
            handler: swift
        swift:
            type:         swift_mailer
            from_email:   'stoppupok64@gmail.com'
            to_email:     'algaev18@gmail.com'
            subject:      'An Error Occurred! %%message%%'
            level:        debug
            formatter:    monolog.formatter.html
            content_type: text/html

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
